name: Run NodePay-2 Script

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 */2 * * *' # Runs every 1 hours

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Install Playwright
        run: npm install playwright && npx playwright install chromium

      - name: Install Xvfb (GUI Emulator)
        run: sudo apt update && sudo apt install -y xvfb

      - name: Clear old NodePay profile
        run: rm -rf /home/runner/Nodepay/nodepay_2

      - name: Clear old extension files
        run: rm -rf /home/runner/Nodepay/extension_2

      - name: Extract Chromium Profile
        run: |
          mkdir -p /home/runner/Nodepay/
          tar -xzvf nodepay_2.tar.gz -C /home/runner/Nodepay/

      - name: Extract Extension
        run: |
          mkdir -p /home/runner/Nodepay/
          tar -xzvf extension_2.tar.gz -C /home/runner/Nodepay/

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run NodePay script
        run: node nodepay-2.js
        env:
          DISPLAY: ':99.0'  # Use Xvfb display for GUI support
